#!/bin/bash

atpg=0
top=""

for arg in $@; do
    if [ "$arg" == "-atpg" ]; then
        atpg=1
    else
        top=$arg
    fi
done

pushd work

xmverilog -compile ../src/*.v
xmverilog -compile ../tb/*.v

xmverilog -compile ../atpg/tb/*.v
xmverilog -compile ../atpg/src/*.v

if [ $atpg == 1 ]; then
    xmverilog +gui +access+r -timescale 1ns/1ps ../atpg/tb/${top}.v
else
    xmverilog +gui +access+r -timescale 1ns/1ps ../tb/${top}.v
fi

popd