#!/bin/bash

# reset control variables
gui=0
topmodule=""
newtopflag=0
top=0

# read and process input arguments
for arg in $@; do
    if [ "$arg" == "-gui" ]; then
	    gui=1
    elif [ $newtopflag == 1 ]; then
        topmodule=$arg
        newtopflag=0
    elif [ "$arg" == "-top" ]; then
	    newtopflag=1
        top=1
    else
        echo "Warning: "${arg}" is not a recognized command option"
        echo ""
    fi
done

echo ""
pushd work

if [ $gui == 1 ]; then
    if [ $top == 1 ]; then
        design_vision -f ../syn/synthesis.tcl -x \"set DESIGN \"${topmodule}\"\"
    else
        design_vision
    fi
else
    if [ $top == 1 ]; then
        dc_shell -f ../syn/synthesis.tcl -x \"set DESIGN \"${topmodule}\"\"
    else
        dc_shell
    fi
fi

popd
